FROM ubuntu:18.04

RUN apt-get update
RUN apt-get -y --fix-missing upgrade

RUN apt-get -y install build-essential

RUN apt-get -y install cmake

RUN apt-get -y install git

RUN apt-get -y install wget

RUN apt-get -y install sudo
